---
name: CGI-Application-Demo-Ajax
version: 1.00
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: 'A search engine using CGI::Application, AJAX and JSON'
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  CGI::Application: 0
  Carp: 0
  Config::Tiny: 0
  DBD::CSV: 0
  DBI: 0
  HTML::Template: 0
  JSON::XS: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  CGI::Application::Demo::Ajax:
    file: lib/CGI/Application/Demo/Ajax.pm
    version: 1.00
  CGI::Application::Demo::Search:
    file: lib/CGI/Application/Demo/Search.pm
    version: 1.00
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
